### ISSUE TITLE
这个错误检测……

### ISSUE THREAD

**Issue by lanyizi** [MrBBBaiXue/RA3.Tools#1]
这个我就不吐槽了（
https://github.com/MrBBBaiXue/RA3.Tools/blob/26423b83720bf95930b5fd37474c233409e6b928/RA3Instance.cs#L180

然后，显而易见Profiles是在使用UTF-16编码记录马甲名称，你这样丢弃高8位的数据，会导致你的代码无法正确处理中文用户名的……
https://github.com/MrBBBaiXue/RA3.Tools/blob/26423b83720bf95930b5fd37474c233409e6b928/RA3Instance.cs#L194

**Comment by richcfno1** [comment]
Fixed in 1.0.8 in commit "rewrite profile functions"
